### ISSUE TITLE
JEII crash on Texture Change

### ISSUE THREAD

**Issue by DrUltraLux** [SnowShock35/jei-integration#24]
The current crash issue with 1.16.5 is caused by JEII generating a null pointer error when any textures are reloaded, either when changing some video settings or applying/removing resource packs or using F3+T. 

You can get around this for now by disabling JEII, making the changes you want, then re-enabling it.

**Comment by freopt** [comment]
can confirm

**Comment by SnowShock35** [comment]
While I was initially able to replicate the issue, after trying multiple times again I can't repeat it. Not entirely sure this is a result of JEI Integration specifically. 

While it's entirely possible it is my mod causing the issue, it's possible that this is correlation rather than causation - i.e., removing the mod might have seemingly stopped the issue happening, but doesn't necessarily mean it's the issue.

I'll keep tabs on this and update this thread as new info comes in.

Thanks for the report 👍🏻
